### ISSUE TITLE
an isssue when trying to license bigip via bigiq using the sdk api

### ISSUE THREAD

**Issue by jikui** [f5devcentral/f5-sdk-python#1]
hi,
I experimented to license an bigip via the bigiq using the sdk api, while the following phenomenon occurred.
From the bigiQ's ui, the license has been assigned to the bigip already while the bigip hasn't yet actually been licensed.
Following is the code snapshot.  What we could do to move this forward?

Thanks in advance.
========================================
import os

from f5sdk.bigiq import ManagementClient
from f5sdk.bigiq.licensing.pools import MemberManagementClient
from f5sdk.logger import Logger

LOGGER = Logger(__name__).get_logger()

def revoke_license(ip, mac):

    mgmt_client = ManagementClient(
            '10.250.11.123',
            user='admin',
            password='f5default')

    member_mgmt_client = MemberManagementClient(mgmt_client)

    return member_mgmt_client.create(
        config={
            'licensePoolName': 'bigip',
            'command': 'assign',
            'address': 10.250.15.152,
            'assignmentType': 'UNREACHABLE',
            'macAddress': mac,
            'hypervisor': 'azure'
        }
    )

if __name__ == '__main__':
    RESPONSE = revoke_license(
        os.environ['F5_BIGIP_MAC']
    )   
    LOGGER.info('Response: %s', RESPONSE)

========================================

**Comment by KrithikaChidambaram** [comment]
Hi Jikui, it seems you have picked assignment type "unreachable" which means the BIG-IQ will not go automatically license the BIG-IP, instead the license text will be included in that method call response as licenseText. This license can then be installed on BIG-IP manually or via BIG-IP API. The license will eventually reside within the /config/bigip.license file on BIG-IP. - https://clouddocs.f5.com/products/big-iq/mgmt-api/v6.0/HowToSamples/bigiq_api_modules/t_license_member_management.html#assigning-a-license-to-an-unreachable-device

If you want the BIG-IQ to go license the BIG-IP, you can provide the following "config" (request body) in the method call - https://clouddocs.f5.com/products/big-iq/mgmt-api/v6.0/HowToSamples/bigiq_api_modules/t_license_member_management.html#assigning-a-license-to-an-unmanaged-device

**Comment by jikui** [comment]
hi krithikaCT,

Much thanks for your help. I will have a try with your suggestion.

THanks
Jikui

**Comment by jikui** [comment]
hi, KrithikaCT,

Your suggestion works. Much thanks and I close the issue now.

Thanks.
