### ISSUE TITLE
python SDK does not define the prober-pool？

### ISSUE THREAD

**Issue by hailong200166** [f5devcentral/f5-sdk-python#5]
I suspect that the python SDK does not define the prober-pool.
Could you pls confirm it? Thanks!
BTW Python the test code and return are as follows:
1.test create Prober-pool failed:
from f5sdk.bigip import ManagementClient
from f5sdk.bigip.dns import DataCentersClient
from f5sdk.bigip.dns import ServersClient
from f5sdk.bigip.dns import PoolsClient
device = ManagementClient('192.168.1.20', user='admin', password='admin')
prober_pool = prober-poolsClient(device)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'prober' is not defined
2. get prober-pool failed
>>> from f5.bigip import ManagementRoot
>>> mgmt = ManagementRoot('192.168.1.20', 'admin', 'admin')
>>> proberpool = mgmt.tm.gtm.prober-pools.pool.load(name='prober-dc')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Program Files\Python38\lib\site-packages\f5\bigip\mixins.py", line 102, in __getattr__
raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.tm.gtm.Gtm'>' object has no attribute 'prober'

**Comment by shyawnkarim** [comment]
The Python SDK does not define prober pools. I've created an enhancement request, internal ID AUTOSDK-318 to get this added.

Thanks for reaching out to us with this issue.

**Comment by hailong200166** [comment]
@shyawnkarim Thank you for your reply！

**Comment by shyawnkarim** [comment]
Closing. This project is no longer being worked on by F5.
